# This workflow will
# - do a clean installation of node dependencies,
# - cache/restore them,
# - run tests across different versions of node

name: CI - Gitflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Gitflow process to trigger"
        type: choice
        default: nothing
        required: true
        options:
          - nothing
          - create
          - merge
          - sync
      release_branch:
        description: "Branch to create"
        type: string
        required: false
      

jobs:
  ci-gitflow-nothing:
    if: github.event.inputs.action == 'nothing'
    runs-on: ubuntu-latest
    steps:
      - name: Do Nothing
        run: echo "Do nothing on ${{ github.event.ref }}"
  ci-gitflow-create:
    if: |
      github.event.inputs.action == 'create'
    runs-on: ubuntu-latest
    steps:
      - name: Create - Missing inputs
        if: github.event.inputs.release_branch == ''
        run: |
          echo "Release branch is missing"
          exit 1
      - uses: actions/checkout@v3
      - name: Create release from develop to ${{ github.event.inputs.release_branch }}
        run: |
          echo "Create release from ${{ github.event.ref }} to ${{ github.event.inputs.release_branch }}"
          git branch ${{ github.event.inputs.release_branch }}
          git push origin ${{ github.event.inputs.release_branch }}
          git checkout ${{ github.event.inputs.release_branch }}
      - name: Create Pull Request
        uses: technote-space/create-pr-action@v2
        with:
          COMMIT_MESSAGE: 'test release pr'
          COMMIT_NAME: 'GitHub Actions'
          COMMIT_EMAIL: 'example@example.com'
          PR_BRANCH_NAME: 'wtf-${PR_ID}'
          PR_TITLE: 'test release pr'
  ci-gitflow-merge:
    if: github.event.inputs.action == 'merge'
    runs-on: ubuntu-latest
    steps:
      - name: Merge release on ...
        run: echo "Merge release on ..."
  ci-gitflow-sync:
    if: github.event.inputs.action == 'sync'
    runs-on: ubuntu-latest
    steps:
      - name: Sync main with ...
        run: echo "Sync main with ..."
