# This workflow will 
# - do a clean installation of node dependencies, 
# - cache/restore them,
# - run tests across different versions of node


name: CI - Tests

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - develop
      - main

jobs:
  ci-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./my-react-app

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: my-react-app/yarn.lock
      - run: npm install -g yarn
      - run: yarn ci
      - run: yarn ci:test
