name: Demo - Inherit Secrets

on:
  workflow_call:
    secrets:
      demoInherit:
        description: "A secret inherit"
        required: true

jobs:
  display-message:
    runs-on: ubuntu-latest
    steps:
      - name: Display a message in case demoInherit exist
        if: ${{ secrets.demoInherit }}
        run: |
          echo "This message is displayed because this reusable workflow recieved the secret demoInherit with inherit option: ${{ secrets.demoInherit }}"
