name: Release Action
# this is only a comment to see it in logs - 001

on:
  push:
    branches:
      - manageReleaseTag

jobs:
  list-of-action-to-release:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - name: Display info
        run: |
          echo "Github event ref branch  : ${{ github.event.ref }}"
          echo "Github actor             : $GITHUB_ACTOR"
          echo "Github branch            : ${GITHUB_REF#refs/heads/}"
          echo "Commit SHA               : ${{ github.sha }}"
          echo "Modified workflows       : $(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})"
          
      - name: Run script
        run: bash ./releaseAction/script.sh ${{ github.event.before }} ${{ github.event.after }}