name: Release - Github Actions

on:
  push:
    branches:
      - develop
      - ImproveReleaseGithubAction

jobs:
  list-of-action-to-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Display info
        run: |
          echo "Github event ref branch  : ${{ github.event.ref }}"
          echo "Github actor             : $GITHUB_ACTOR"
          echo "Github branch            : ${GITHUB_REF#refs/heads/}"

      - name: Fetch tags
        run: |
          git fetch --tag

      - name: Create tags
        run: |
          versions=$(cat ./release.txt)

          while read n; do 
            echo "Name $n"
            if grep -q -w $n <<< $(git tag -l); then
              echo "$n already exist"
            else
              curl \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
                https://api.github.com/repos/grasdouble/github-action/releases \
                -d '{"tag_name":"'"${n}"'","target_commitish":"develop","name":"'"${n}"'","body":"Release","draft":false,"prerelease":false,"generate_release_notes":false}'
            fi
          done <<< "$versions"
