name: Release Action

on:
  push:
    branches:
      - develop

jobs:
  list-of-action-to-release:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - name: Display info
        run: |
          echo "Github event ref branch  : ${{ github.event.ref }}"
          echo "Github actor             : $GITHUB_ACTOR"
          echo "Github branch            : ${GITHUB_REF#refs/heads/}"
          echo "Commit SHA               : ${{ github.sha }}"
          echo "Modified workflows       : $(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})"
          
      - name: Run script
        run: bash ./scripts/releaseAction/script.sh ${{ github.event.before }} ${{ github.event.after }}
        #To test locally -> bash ./scripts/releaseAction/script.sh e994f6d09c0fcb247dc628b2aca5878d00d39d3e 14bd3be9b33ba23d0b389f58245420fb8a2c7463