name: Release - Github Actions

on:
  push:
    branches:
      - develop
      - add/tool-plantuml-generator

jobs:
  list-of-action-to-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Display info
        run: |
          echo "Github event ref branch  : ${{ github.event.ref }}"
          echo "Github actor             : $GITHUB_ACTOR"
          echo "Github branch            : ${GITHUB_REF#refs/heads/}"

#      - name: List of modified list
        