name: Tool - PlantUml Generator

on:
  push:
    pull_request:
      - develop

jobs:
  list-of-action-to-generate-uml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Display info
        run: |
          echo "Github event ref branch  : ${{ github.event.ref }}"
          echo "Github actor             : $GITHUB_ACTOR"
          echo "Github branch            : ${GITHUB_REF#refs/heads/}"

      - name: List of modified list
        run: |
          echo "Git diff                 : $(git diff --name-only ${{ github.event.before}} ${{github.event.after}})"
        