name: Tool - PlantUml Generator

on:
  push:
    pull_request:
      - develop

jobs:
  list-of-action-to-generate-uml:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Display info
        run: |
          echo "Github event ref branch  : ${{ github.event.ref }}"
          echo "Github actor             : $GITHUB_ACTOR"
          echo "Github branch            : ${GITHUB_REF#refs/heads/}"
          echo "Github pr number         : ${{ github.event.number }}"

      - name: List of modified list
        run: |
          curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
            https://api.github.com/repos/grasdouble/github-action/pulls/${{ github.event.number }}/files
          echo "Git diff                 : $(echo $modifiedFiles)"